"use client";

import { useState, type MouseEvent } from "react";
import dynamic from "next/dynamic";
import { saveAddressAction } from "@/lib/actions/address";
import { SheetDescription, SheetTitle } from "../ui/sheet";
import {
  BriefcaseBusiness,
  Heading1Icon,
  Heart,
  Home,
  MapPin,
  Plus,
} from "lucide-react";
import { Controller, useForm, useWatch } from "react-hook-form";
import { Address } from "@/lib/types/user.types";
import { RadioGroup, RadioGroupItem } from "../ui/radio-group";
import { Label } from "@/components/ui/label";
import { Field, FieldDescription, FieldError, FieldLabel } from "../ui/field";
import { Input } from "../ui/input";
import { Button } from "../ui/button";

import { useLayoutStore } from "@/lib/stores/layoutStore";
import { useUserStore } from "@/lib/stores/userStore";

const Map = dynamic(() => import("./Map").then((mod) => mod.Map), {
  ssr: false,
  loading: () => (
    <div className="h-[150px] w-[390px] animate-pulse rounded-md bg-neutral-100" />
  ),
});

export function AddressForm() {
  const [customLabel, setCustomLabel] = useState("");
  const { closeAddressModal } = useLayoutStore((state) => state);
  const { tempAddress } = useUserStore((state) => state);
  if (!tempAddress) return null;
  const {
    osmId,
    addressLine1,
    addressLine2,
    city,
    label,
    isDefault,
    coords,
    note,
    id,
  } = tempAddress;
  const form = useForm<Address>({
    defaultValues: {
      osmId,
      addressLine1,
      addressLine2,
      city,
      label,
      isDefault: true,
      coords,
      note,
      id, // This will be generated by the backend, so we can leave it empty here
    },
  });
  const selectedLabel = useWatch({
    control: form.control,
    name: "label",
  });

  const onSubmit = async (data: Address) => {
    const labelText = data.label === "Other" ? customLabel : data.label;
    const payload: Address = {
      ...data,
      label: labelText,
    };
    await saveAddressAction(payload);
    closeAddressModal();
  };
  const missingInfo = "street and house number";
  const placeholderMissingInfo = "street and house number";
  // ui related
  // const missingInfo = !tempAddress.addressLine1
  //   ? "address"
  //   : !tempAddress.street
  //     ? "street"
  //     : null;
  // const placeholderMissingInfo = !tempAddress.addressLine1
  //   ? "Street and house number"
  //   : !tempAddress.street
  //     ? "Street name"
  //     : "";
  return (
    <form onSubmit={form.handleSubmit(onSubmit)} className="w-full">
      <Map
        // key="foodpanda-map-v2"
        zoom={25}
        className="h-[150px] max-w-[390px] overflow-clip px-2"
        position={[
          tempAddress?.coords.lat ?? 23.7524788,
          tempAddress?.coords.lng ?? 90.4176482,
        ]}
      />
      <div className="px-4">
        <div className="mt-4 flex items-end justify-between gap-1">
          <div>
            <SheetTitle className="flex items-center text-lg font-semibold text-neutral-900">
              <span className="-translate-x-0.5">
                <MapPin />
              </span>
              {tempAddress?.city}
            </SheetTitle>
            <SheetDescription className="mt-1 text-xs font-medium text-neutral-700">
              {tempAddress?.street}
            </SheetDescription>
          </div>
          <button type="button">Edit</button>
        </div>

        {/* divider */}
        <div className="my-4 h-0.5 w-full bg-gray-400"></div>
        {!!missingInfo && (
          <div>
            <h1 className="text-sm font-semibold text-neutral-900">
              We&apos;re missing your {missingInfo}
            </h1>
            <Controller
              name="addressLine1"
              control={form.control}
              rules={{ required: "Address is required" }}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="mt-3 gap-2">
                  <FieldLabel htmlFor={field.name}>{missingInfo}</FieldLabel>
                  <Input
                    {...field}
                    id={field.name}
                    aria-invalid={fieldState.invalid}
                    placeholder={placeholderMissingInfo}
                    autoComplete="off"
                    className="h-11"
                  />
                  <FieldDescription>
                    Add street and house number so riders can find you.
                  </FieldDescription>
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />
          </div>
        )}

        <div>
          <Controller
            name="addressLine2"
            control={form.control}
            render={({ field, fieldState }) => (
              <Field data-invalid={fieldState.invalid} className="mt-2 gap-2">
                <FieldLabel htmlFor={field.name}>Address Details</FieldLabel>
                <Input
                  {...field}
                  id={field.name}
                  aria-invalid={fieldState.invalid}
                  placeholder="Apartment #"
                  autoComplete="off"
                  className="h-11"
                />
                <FieldDescription>
                  Apartment, unit, floor, or building details.
                </FieldDescription>
                {fieldState.invalid && (
                  <FieldError errors={[fieldState.error]} />
                )}
              </Field>
            )}
          />

          <Controller
            name="note"
            control={form.control}
            render={({ field, fieldState }) => (
              <Field data-invalid={fieldState.invalid} className="mt-2 gap-2">
                <FieldLabel htmlFor={field.name}>Delivery Note</FieldLabel>
                <Input
                  {...field}
                  id={field.name}
                  aria-invalid={fieldState.invalid}
                  placeholder="Note to rider - e.g. building, landmark"
                  autoComplete="off"
                  className="h-11"
                />
                <FieldDescription>
                  Optional instructions to help delivery arrive faster.
                </FieldDescription>
                {fieldState.invalid && (
                  <FieldError errors={[fieldState.error]} />
                )}
              </Field>
            )}
          />
        </div>

        {/* label */}
        <div className="mt-4">
          <p className="text-sm font-semibold text-neutral-900">Add a Label</p>

          <Controller
            name="label"
            control={form.control}
            render={({ field, fieldState }) => (
              <Field data-invalid={fieldState.invalid} className="mt-2 gap-2">
                <FieldLabel htmlFor={field.name}>Address Label</FieldLabel>
                <AddressLabelSelector
                  label={field.value ?? ""}
                  onValueChange={field.onChange}
                />
                <FieldDescription>
                  Choose where this address belongs.
                </FieldDescription>
                {fieldState.invalid && (
                  <FieldError errors={[fieldState.error]} />
                )}
              </Field>
            )}
          />

          {selectedLabel === "Other" && (
            <input
              name="customLabel"
              value={customLabel}
              onChange={(e) => setCustomLabel(e.target.value)}
              placeholder="Custom"
              className="mt-3 h-11 w-full rounded-md border border-neutral-300 px-3 text-sm text-neutral-900 placeholder:text-neutral-400 focus:border-neutral-400 focus:outline-none"
            />
          )}
        </div>

        {/* save */}
        <button
          type="submit"
          className="bg-primary text-card mt-6 h-11 w-full rounded-md text-sm font-semibold"
        >
          Save and continue
        </button>
      </div>
    </form>
  );
}

function AddressLabelSelector({
  label,
  onValueChange,
}: {
  label: string;
  onValueChange: (value: string) => void;
}) {
  const handleLabelClick = (
    event: MouseEvent<HTMLLabelElement>,
    value: string,
  ) => {
    if (label === value) {
      // Prevent the hidden radio item from re-selecting the same value.
      event.preventDefault();
      onValueChange("");
    }
  };

  return (
    <RadioGroup
      value={label}
      onValueChange={onValueChange}
      className="mt-2 flex flex-wrap gap-2"
    >
      <div className="flex items-center gap-3">
        <RadioGroupItem value="Home" id="label-home" className="sr-only" />
        <Label
          htmlFor="label-home"
          onClick={(event) => handleLabelClick(event, "Home")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Home"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <Home className="size-4" />
          Home
        </Label>
      </div>

      <div className="flex items-center gap-3">
        <RadioGroupItem value="Work" id="label-work" className="sr-only" />
        <Label
          htmlFor="label-work"
          onClick={(event) => handleLabelClick(event, "Work")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Work"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <BriefcaseBusiness className="size-4" />
          Work
        </Label>
      </div>

      <div className="flex items-center gap-3">
        <RadioGroupItem
          value="Partner"
          id="label-partner"
          className="sr-only"
        />
        <Label
          htmlFor="label-partner"
          onClick={(event) => handleLabelClick(event, "Partner")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Partner"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <Heart className="size-4" />
          Partner
        </Label>
      </div>

      <div className="flex items-center gap-3">
        <RadioGroupItem value="Other" id="label-other" className="sr-only" />
        <Label
          htmlFor="label-other"
          onClick={(event) => handleLabelClick(event, "Other")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Other"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <Plus className="size-4" />
          Other
        </Label>
      </div>
    </RadioGroup>
  );
}
