"use client";

import { useState, type MouseEvent } from "react";
import dynamic from "next/dynamic";
import { LocationDetails } from "@/lib/types/location.types";
import { saveAddressAction } from "@/lib/actions/address";
import { SheetDescription, SheetTitle } from "../ui/sheet";
import {
  BriefcaseBusiness,
  Heading1Icon,
  Heart,
  Home,
  MapPin,
  Plus,
} from "lucide-react";
import { Controller, useForm, useWatch } from "react-hook-form";
import { UserAddress } from "@/lib/types/user.types";
import { RadioGroup, RadioGroupItem } from "../ui/radio-group";
import { Label } from "@/components/ui/label";
import { Field, FieldDescription, FieldError, FieldLabel } from "../ui/field";
import { Input } from "../ui/input";
import { Button } from "../ui/button";

const Map = dynamic(() => import("./Map").then((mod) => mod.Map), {
  ssr: false,
  loading: () => (
    <div className="h-[150px] w-[390px] animate-pulse rounded-md bg-neutral-100" />
  ),
});

export function AddressForm({
  selectedLocation,
}: {
  selectedLocation: LocationDetails;
}) {
  const [customLabel, setCustomLabel] = useState("");

  const form = useForm<UserAddress>({
    defaultValues: {
      userId: "",
      osmId: selectedLocation.osmId,
      addressLine1: `${selectedLocation.house} ${selectedLocation.street}`,
      addressLine2: "",
      city: selectedLocation.city,
      label: "",
      isDefault: false,
      coords: selectedLocation.coords,
      note: "",
      id: null, // This will be generated by the backend, so we can leave it empty here
    },
  });
  const selectedLabel = useWatch({
    control: form.control,
    name: "label",
  });

  const onSubmit = async (data: UserAddress) => {
    const labelText = data.label === "Other" ? customLabel : data.label;
    const payload: UserAddress = {
      ...data,
      label: labelText,
    };

    await saveAddressAction(payload);
  };

  // ui related
  const { street, house } = selectedLocation || {};
  const missingInfo = [
    !street ? "street" : null,
    !house ? "house number" : null,
  ]
    .filter(Boolean)
    .join(" / ");
  const placeholderMissingInfo = missingInfo
    .split(" ")
    .map((word) => (word ? word.charAt(0).toUpperCase() + word.slice(1) : word))
    .join(" ");
  return (
    <form onSubmit={form.handleSubmit(onSubmit)} className="w-full">
      <Map
        // key="foodpanda-map-v2"
        zoom={25}
        className="h-[150px] max-w-[390px] overflow-clip px-2"
        position={[
          selectedLocation?.coords.lat ?? 23.7524788,
          selectedLocation?.coords.lng ?? 90.4176482,
        ]}
      />
      <div className="px-4">
        <div className="mt-4 flex items-center gap-1">
          <MapPin size={18} />
          <div>
            <Heading1Icon className="text-lg font-semibold text-neutral-900">
              {selectedLocation?.city}
            </Heading1Icon>
            <p className="text-xs font-medium text-neutral-700">
              {selectedLocation.street}
            </p>
          </div>
        </div>
        <div className="flex w-full justify-end">
          <button type="button">Edit</button>
        </div>
        {/* divider */}
        <div className="my-4 h-0.5 w-full bg-gray-400"></div>
        {!!missingInfo && (
          <div>
            <h1 className="text-sm font-semibold text-neutral-900">
              We&apos;re missing your {missingInfo}
            </h1>
            <Controller
              name="addressLine1"
              control={form.control}
              rules={{ required: "Address is required" }}
              render={({ field, fieldState }) => (
                <Field data-invalid={fieldState.invalid} className="mt-3 gap-2">
                  <FieldLabel htmlFor={field.name}>{missingInfo}</FieldLabel>
                  <Input
                    {...field}
                    id={field.name}
                    aria-invalid={fieldState.invalid}
                    placeholder={placeholderMissingInfo}
                    autoComplete="off"
                    className="h-11"
                  />
                  <FieldDescription>
                    Add street and house number so riders can find you.
                  </FieldDescription>
                  {fieldState.invalid && (
                    <FieldError errors={[fieldState.error]} />
                  )}
                </Field>
              )}
            />
          </div>
        )}

        <div>
          <Controller
            name="addressLine2"
            control={form.control}
            render={({ field, fieldState }) => (
              <Field data-invalid={fieldState.invalid} className="mt-2 gap-2">
                <FieldLabel htmlFor={field.name}>Address Details</FieldLabel>
                <Input
                  {...field}
                  id={field.name}
                  aria-invalid={fieldState.invalid}
                  placeholder="Apartment #"
                  autoComplete="off"
                  className="h-11"
                />
                <FieldDescription>
                  Apartment, unit, floor, or building details.
                </FieldDescription>
                {fieldState.invalid && (
                  <FieldError errors={[fieldState.error]} />
                )}
              </Field>
            )}
          />

          <Controller
            name="note"
            control={form.control}
            render={({ field, fieldState }) => (
              <Field data-invalid={fieldState.invalid} className="mt-2 gap-2">
                <FieldLabel htmlFor={field.name}>Delivery Note</FieldLabel>
                <Input
                  {...field}
                  id={field.name}
                  aria-invalid={fieldState.invalid}
                  placeholder="Note to rider - e.g. building, landmark"
                  autoComplete="off"
                  className="h-11"
                />
                <FieldDescription>
                  Optional instructions to help delivery arrive faster.
                </FieldDescription>
                {fieldState.invalid && (
                  <FieldError errors={[fieldState.error]} />
                )}
              </Field>
            )}
          />
        </div>

        {/* label */}
        <div className="mt-4">
          <p className="text-sm font-semibold text-neutral-900">Add a Label</p>

          <Controller
            name="label"
            control={form.control}
            render={({ field, fieldState }) => (
              <Field data-invalid={fieldState.invalid} className="mt-2 gap-2">
                <FieldLabel htmlFor={field.name}>Address Label</FieldLabel>
                <AddressLabelSelector
                  label={field.value ?? ""}
                  onValueChange={field.onChange}
                />
                <FieldDescription>
                  Choose where this address belongs.
                </FieldDescription>
                {fieldState.invalid && (
                  <FieldError errors={[fieldState.error]} />
                )}
              </Field>
            )}
          />

          {selectedLabel === "Other" && (
            <input
              name="customLabel"
              value={customLabel}
              onChange={(e) => setCustomLabel(e.target.value)}
              placeholder="Custom"
              className="mt-3 h-11 w-full rounded-md border border-neutral-300 px-3 text-sm text-neutral-900 placeholder:text-neutral-400 focus:border-neutral-400 focus:outline-none"
            />
          )}
        </div>

        {/* save */}
        <button
          type="submit"
          className="bg-primary text-card mt-6 h-11 w-full rounded-md text-sm font-semibold"
        >
          Save and continue
        </button>
      </div>
    </form>
  );
}

function AddressLabelSelector({
  label,
  onValueChange,
}: {
  label: string;
  onValueChange: (value: string) => void;
}) {
  const handleLabelClick = (
    event: MouseEvent<HTMLLabelElement>,
    value: string,
  ) => {
    if (label === value) {
      // Prevent the hidden radio item from re-selecting the same value.
      event.preventDefault();
      onValueChange("");
    }
  };

  return (
    <RadioGroup
      value={label}
      onValueChange={onValueChange}
      className="mt-2 flex flex-wrap gap-2"
    >
      <div className="flex items-center gap-3">
        <RadioGroupItem value="Home" id="label-home" className="sr-only" />
        <Label
          htmlFor="label-home"
          onClick={(event) => handleLabelClick(event, "Home")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Home"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <Home className="size-4" />
          Home
        </Label>
      </div>

      <div className="flex items-center gap-3">
        <RadioGroupItem value="Work" id="label-work" className="sr-only" />
        <Label
          htmlFor="label-work"
          onClick={(event) => handleLabelClick(event, "Work")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Work"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <BriefcaseBusiness className="size-4" />
          Work
        </Label>
      </div>

      <div className="flex items-center gap-3">
        <RadioGroupItem
          value="Partner"
          id="label-partner"
          className="sr-only"
        />
        <Label
          htmlFor="label-partner"
          onClick={(event) => handleLabelClick(event, "Partner")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Partner"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <Heart className="size-4" />
          Partner
        </Label>
      </div>

      <div className="flex items-center gap-3">
        <RadioGroupItem value="Other" id="label-other" className="sr-only" />
        <Label
          htmlFor="label-other"
          onClick={(event) => handleLabelClick(event, "Other")}
          className={`inline-flex h-8 cursor-pointer items-center gap-1 rounded-full border px-3 text-sm ${
            label === "Other"
              ? "border-neutral-900 bg-neutral-900 text-white"
              : "border-neutral-300 bg-white text-neutral-700"
          }`}
        >
          <Plus className="size-4" />
          Other
        </Label>
      </div>
    </RadioGroup>
  );
}
