import type { Metadata } from "next";
import Header from "@/components/MainHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <body className="font-sans">
      <Header />
      <main>{children}</main>
      {/* <AddressDrawer />
        <AddressPickerDrawer /> */}
    </body>
  );
}
